### ISSUE TITLE
Idea: have guides stick to the cursor

### ISSUE THREAD

**Issue by drawcard** [Mark2Mark/show-stems-pro-plugin#3]
I was wondering if you might consider creating a preference for having the stem guides stick to the cursor, as it moves around the canvas - a little bit like how [Show Crosshair](https://github.com/mekkablue/ShowCrosshair) works?

This would allow users to quickly mouse over an area to check measurements while it's being adjusted. 

I also love using a crosshair while working and it would be a nice bonus having that :)

**Comment by Mark2Mark** [comment]
It should be implemented now. Version is 3.1.4 (build 12)

**Comment by drawcard** [comment]
Just tested this, it works beautifully, thanks again :)

**Comment by Mark2Mark** [comment]
Thanks for letting me know.

Out of curiosity: Did the update come all by itself, or did you have to uninstall and reinstall the plugin?

**Comment by drawcard** [comment]
I had to uninstall and reinstall, then restart Glyphs
